config/routes.rb
Rails.application.routes.draw do
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Defines the root path route ("/")
    # root "posts#index"
    root to: "boards#index"

    resource :profile, controller: :profile, only: [ :show, :update ]
    resources :reservations, only: [ :index, :create, :delete, :destroy ]
    resources :time_slots, only: [ :index, :create, :new, :destroy, :edit ]
    resources :rooms, only: [ :index, :create, :new, :destroy, :edit, :update ]
    resources :users, only: [ :index, :create, :new, :destroy ] do
        member do
            patch "promote_to_regular"
            patch "promote_to_admin"
            patch "demote_to_guest"
        end
        resources :reservations
    end
    get "pending", to: "users#pending"
    get "/login", to: "session#new"
    post "/login", to: "session#create"
    get "/login/callback", to: "session#callback"
    delete "/logout", to: "session#destroy"  

    get "/boards/:id/(:date)", to: "boards#show",
        constraints: { :date => /\d{4}-\d{2}-\d{2}/ },
        as: :board

    get :rules, to: "rules#index" 
    get :limits, to: "limits#index" 
    put :limits, to: "limits#update" 
    
    # 忘記密碼
    get "/forgot-password", to: "users#forgot_password_form"
    post "/forgot-password", to: "users#forgot_password"
    get "/reset-password", to: "users#reset_password_form"
    post "/reset-password", to: "users#reset_password"

    delete '/users/:id/clear_reservations', 
        to: 'users#clear_reservations', 
        as: 'clear_reservations'

end

app/controllers/session_controller.rb
require 'net/http'
require 'net/https'

class SessionController < ApplicationController
    def new
    end

    def create
        case params[:login_method]
            when "password"
                user = User.find_by(name: params[:name])
                if !!user && user.authenticate(params[:password])
                    create_session(user.id)
                else
                    flash.now[:alert] = "帳號或密碼錯誤" # i18n: Incorrect student ID or password.
                    render :new, status: :unauthorized
                end
            when "oauth"
                redirect_to(authorization_url, allow_other_host: true)
        end
    end

    def destroy
        reset_session
        # 回到登入頁面
        redirect_to login_path, notice: "登出成功" # i18n: Logout successfully.
    end    

    def callback
        code = params[:code]
        access_token = get_access_token(code)
        user_data = get_user_data(access_token)
        login_or_create_user(user_data)
    end
    
    private

    def authorization_url
        authorization_endpoint = "#{Rails.application.config.oauth_server}/o/authorize"
        client_id = Rails.application.credentials.oauth.client_id
        scope = Rails.application.config.oauth_scope
        "#{authorization_endpoint}?response_type=code&client_id=#{client_id}&scope=#{scope}"
    end
    
    def get_access_token(code)
        # TODO 測試/正式 client_id, client_secret 分離
        uri = URI("#{Rails.application.config.oauth_server}/o/token/")
        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = true
        access_request = Net::HTTP::Post.new(uri)
        access_request.set_form_data({
          "grant_type" => "authorization_code",
          "code" => code,
          "client_id" => Rails.application.credentials.oauth.client_id,
          "client_secret" => Rails.application.credentials.oauth.client_secret,
          "redirect_uri" => request.base_url + login_callback_path
        })
        response = http.request(access_request)
        JSON.parse(response.body)["access_token"]
    end
    
    def get_user_data(access_token)
        uri = URI("#{Rails.application.config.oauth_server}/api/#{Rails.application.config.oauth_scope}/")
        request = Net::HTTP::Get.new(uri)
        request["Authorization"] = "Bearer #{access_token}"
        response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) do |http|
          http.request(request)
        end
        JSON.parse(response.body)
    end
    
    def login_or_create_user(user_data)
        name = user_data["username"]
        email = user_data["email"]
    
        user = User.find_or_initialize_by(name: name)

        if user.new_record?
            # 註冊新帳號
            user.email = email
            user.nick = name
            user.role = :guest
            user.password_digest =BCrypt::Password.create(SecureRandom.hex(10))
            user.save
        end
    
        create_session(user.id)
    end
    
    def create_session(id)
        session[:user_id] = id
        redirect_to (session.delete(:return_to) || root_path), notice: "登入成功" # i18n: Login successfully.
    end
    
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/new.html.erb
<div class="flex-auto bg-slate-100 flex">
  <div class="w-7/12 hidden lg:block flex-grow">
    <%= image_tag 'login.jpg', class: "object-cover w-full h-full" ,alt: "Login Meme" %>
  </div>
  <div class="w-5/12 flex-grow px-6 flex items-center">
    <div class="w-full">
      <h1 class="mb-4 text-4xl text-gray-800">登入</h1>
      <%= form_tag "/login" do %>
        <%= hidden_field_tag(:login_method, 'password') %>
        <div class="mb-6">
          <%= label_tag :name, "學號", class: "block font-bold text-gray-600 mb-1" %>
          <%= text_field_tag :name, nil, class: "w-full py-2 px-3 border leading-tight appearance-none rounded shadow focus:outline-none focus:shadow-outline" %>
        </div>
        <div class="mb-6">
          <%= label_tag :password, "密碼", class: "block font-bold text-gray-600 mb-1" %>
          <%= password_field_tag :password, nil, class: "w-full py-2 px-3 border leading-tight appearance-none rounded shadow focus:outline-none focus:shadow-outline" %>
        </div>
        <div>
          <%= submit_tag "登入", class: "block w-full py-2 my-4 bg-blue-500 text-white rounded cursor-pointer" %>
        </div>
      <% end %>
      <p class="text-center text-gray-400">或是用單一入口登入/註冊</p>
      <%= button_to(
          "使用 NYCU 單一入口登入/註冊", 
          login_path, method: :post, 
          params: { login_method: 'oauth' },
          data: {turbo: "false"}, 
          class: "block w-full py-2 my-4 bg-indigo-500 text-white rounded cursor-pointer"
        ) %>
      <p class="text-center text-gray-400">還沒有帳號？<%= link_to "立即註冊", new_user_path, class: "text-blue-500" %></p>
      <p class="text-center text-gray-400">忘記密碼？<%= link_to "重設密碼", forgot_password_path, class: "text-blue-500" %></p>
    </div>
  </div>
</div>