config/routes.rb
Rails.application.routes.draw do
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Defines the root path route ("/")
    # root "posts#index"
    root to: "boards#index"

    resource :profile, controller: :profile, only: [ :show, :update ]
    resources :reservations, only: [ :index, :create, :delete, :destroy ]
    resources :time_slots, only: [ :index, :create, :new, :destroy, :edit ]
    resources :rooms, only: [ :index, :create, :new, :destroy, :edit, :update ]
    resources :users, only: [ :index, :create, :new, :destroy ] do
        member do
            patch "promote_to_regular"
            patch "promote_to_admin"
            patch "demote_to_guest"
        end
        resources :reservations
    end
    get "pending", to: "users#pending"
    get "/login", to: "session#new"
    post "/login", to: "session#create"
    get "/login/callback", to: "session#callback"
    delete "/logout", to: "session#destroy"  

    get "/boards/:id/(:date)", to: "boards#show",
        constraints: { :date => /\d{4}-\d{2}-\d{2}/ },
        as: :board

    get :rules, to: "rules#index" 
    get :limits, to: "limits#index" 
    put :limits, to: "limits#update" 
    
    # 忘記密碼
    get "/forgot-password", to: "users#forgot_password_form"
    post "/forgot-password", to: "users#forgot_password"
    get "/reset-password", to: "users#reset_password_form"
    post "/reset-password", to: "users#reset_password"

    delete '/users/:id/clear_reservations', 
        to: 'users#clear_reservations', 
        as: 'clear_reservations'

end

app/models/time_slot.rb
class TimeSlot < ApplicationRecord
end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController
    before_action :set_time_slot, only: %i[ destroy edit ]
    before_action :require_login
    before_action :require_non_guest

    def index
        @time_slots = TimeSlot.all
    end

    def new
        @time_slot = TimeSlot.new
    end

    def create
        @time_slot = TimeSlot.new(time_slot_params)

        # TODO 檢查時段重疊

        if @time_slot.save
            redirect_to time_slot_url, notice: "新增成功" # i18n: Time slot was successfully created.
        else
            flash.now[:alert] = "新增失敗" # i18n
            render :new, status: :unprocessable_entity
        end

    end

    def destroy

        if @time_slot.destroy
            redirect_to time_slots_url, notice: "刪除成功" # i18n: Time slot was successfully destroyed.
        else
            flash.now[:alert] = "刪除失敗" # i18n
            render :index, status: :unprocessable_entity # i18n: Failed to destroy the time slot.
        end

    end

    def edit
    end

    def update

        if @time_slot.update(time_slot_params)
            redirect_to time_slots_url, notice: "更新成功" # TODO i18n: Time slot was successfully updated.
        else
            flash.now[:alert] = "更新失敗" # i18n: Failed to update the time slot.
            render :index, status: :unprocessable_entity
        end

    end

    private

    def time_slot_params
        params.require(:time_slot).permit(:name, :start_at, :end_at)
    end

    def set_time_slot
        @time_slot = TimeSlot.find(params[:id])
    end

end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/time_slots/_form.html.erb
<%= form_with(model: time_slot) do |form| %>
  <div class="mb-4">
    <%= form.label :name, "名稱", class: "block font-bold text-gray-700 mb-1" %>
    <%= form.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :start_at, "開始時間", class: "block font-bold text-gray-700 mb-1" %>
    <%= form.time_field :start_at, class: "shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :end_at, "結束時間", class: "block font-bold text-gray-700 mb-1" %>
    <%= form.time_field :end_at, class: "shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div>
    <%= form.submit "確定", class: "cursor-pointer bg-blue-500 px-3 py-2 rounded text-white" %>
  </div>
<% end %>

app/views/time_slots/edit.html.erb
<div>
    <h1 class="text-4xl">編輯時段</h1>
    <div class="py-5">
        <%= render "form", time_slot: @time_slot %>
    </div>
    <div>
    <%= link_to "回到時段列表", time_slots_path, class: "text-blue-500" %>
    </div>
</div>

app/views/time_slots/index.html.erb
<div class="w-full lg:py-10">
  <div class=" lg:mx-32 py-2 px-2 lg:py-12 lg:px-16 bg-white rounded lg:rounded-3xl shadow-md overflow-x-auto">
    <table class="table-auto w-full text-left">
      <thead>
        <tr>
          <th class="pb-2 text-xl">名稱</th>
          <th class="pb-2 text-xl">開始時間</th>
          <th class="pb-2 text-xl">結束時間</th>
          <th class="pb-2 text-xl"></th>
          <th class="pb-2 text-xl"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td colspan="4"><%= link_to "新增時段", new_time_slot_path, class: "text-blue-500"%></td>
        </tr>
        <% @time_slots.each do |time_slot| %>
          <tr class="border-t border-slate-200">
            <td class="py-2">
              <div class="px-2 py-1">
                <%= time_slot.name %>
              </div>
            </td>
            <td class="py-2">
              <div class="px-2 py-1">
                <%= time_slot.start_at.strftime("%H:%M") %>
              </div>
            </td>
            <td class="py-2">
              <div class="px-2 py-1">
                <%= time_slot.end_at.strftime("%H:%M") %>
              </div>
            </td>
            <td class="py-2 text-right min-w-28">
              <%= 
              link_to "編輯", 
              edit_time_slot_path(time_slot),
              class: "block w-fit px-3 py-2 rounded bg-blue-500 hover:bg-blue-600 text-white"
              %>
            </td>
            <td class="py-2 text-right min-w-28">
              <%= 
              link_to "刪除", 
              time_slot, 
              method: :delete,
              data: { turbo_method: :delete, turbo_confirm: "確定刪除？" },
              class: "block w-fit px-3 py-2 rounded bg-red-500 hover:bg-red-600 text-white"
              %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/time_slots/new.html.erb
<div>
    <h1 class="text-4xl">新增時段</h1>
    <div class="py-5">
        <%= render "form", time_slot: @time_slot %>
    </div>
    <div>
    <%= link_to "回到時段列表", time_slots_path, class: "text-blue-500" %>
    </div>
</div>