config/routes.rb
Rails.application.routes.draw do
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Defines the root path route ("/")
    # root "posts#index"
    root to: "boards#index"

    resource :profile, controller: :profile, only: [ :show, :update ]
    resources :reservations, only: [ :index, :create, :delete, :destroy ]
    resources :time_slots, only: [ :index, :create, :new, :destroy, :edit ]
    resources :rooms, only: [ :index, :create, :new, :destroy, :edit, :update ]
    resources :users, only: [ :index, :create, :new, :destroy ] do
        member do
            patch "promote_to_regular"
            patch "promote_to_admin"
            patch "demote_to_guest"
        end
        resources :reservations
    end
    get "pending", to: "users#pending"
    get "/login", to: "session#new"
    post "/login", to: "session#create"
    get "/login/callback", to: "session#callback"
    delete "/logout", to: "session#destroy"  

    get "/boards/:id/(:date)", to: "boards#show",
        constraints: { :date => /\d{4}-\d{2}-\d{2}/ },
        as: :board

    get :rules, to: "rules#index" 
    get :limits, to: "limits#index" 
    put :limits, to: "limits#update" 
    
    # 忘記密碼
    get "/forgot-password", to: "users#forgot_password_form"
    post "/forgot-password", to: "users#forgot_password"
    get "/reset-password", to: "users#reset_password_form"
    post "/reset-password", to: "users#reset_password"

    delete '/users/:id/clear_reservations', 
        to: 'users#clear_reservations', 
        as: 'clear_reservations'

end

app/models/room.rb
class Room < ApplicationRecord
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :set_room, only: %i[ destroy edit update ]
    before_action :require_login
    before_action :require_non_guest
    before_action :require_admin, except: %i[ index ] # 一般社員只能看房間列表

    def index
        @rooms = Room.all
    end

    def new
        @room = Room.new
    end

    def create
        @room = Room.new(room_params)

        # TODO 檢查時段重疊

        if @room.save
            redirect_to rooms_url, notice: "新增成功" # i18n: Room was successfully created.
        else
            flash.now[:alert] = "新增失敗" # i18n
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        if @room.destroy
            redirect_to rooms_url, notice: "刪除成功" # i18n: Room was successfully destroyed.
        else
            flash.now[:alert] = "刪除失敗" # i18n
            render :index, status: :unprocessable_entity # i18n: Failed to destroy the room.
        end
    end

    def edit
    end

    def update
        if @room.update(room_params)
            redirect_to rooms_url, notice: "更新成功" # TODO i18n: Room was successfully updated.
        else
            flash.now[:alert] = "更新失敗" # i18n: Failed to update the room.
            render :index, status: :unprocessable_entity
        end
    end

    private

    def room_params
        params.require(:room).permit(:name, :password, :color)
    end

    def set_room
        @room = Room.find(params[:id])
    end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <div class="mb-4">
    <%= form.label :name, "名稱", class: "block font-bold text-gray-700 mb-1" %>
    <%= form.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :password, "門鎖密碼", class: "block font-bold text-gray-700 mb-1" %>
    <%= form.text_field :password, class: "shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :color, "顏色", class: "block font-bold text-gray-700 mb-1" %>
    <%= form.text_field :color, class: "shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div>
    <%= form.submit "確定", class: "cursor-pointer w-full py-2 block bg-blue-500 rounded text-white" %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<div class="container mx-auto lg:py-10">
  <div class="w-1/2 mx-auto bg-white rounded-3xl py-12 px-16">
    <h1 class="text-4xl text-center">編輯房間</h1>
    <div class="py-5">
      <%= render "form", room: @room %>
    </div>
    <div class="text-center">
      <%= link_to "回到房間列表", rooms_path, class: "text-blue-500" %>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="w-full lg:py-10">
  <div class=" lg:mx-32 py-2 px-2 lg:py-12 lg:px-16 bg-white rounded lg:rounded-3xl shadow-md overflow-x-auto">
    <table class="table-auto w-full text-left">
      <thead>
        <tr>
          <th class="pb-4 text-xl">琴房</th>
          <th class="pb-4 text-xl">門鎖密碼</th>
          <th class="pb-4 text-xl">顏色</th>
          <th class="pb-4 text-xl"></th>
          <th class="pb-4 text-xl"></th>
        </tr>
      </thead>
      <tbody>
        <% if current_user&.admin? %>
          <tr>
            <td colspan="4"><%= link_to "新增房間", new_room_path, class: "text-blue-500"%></td>
          </tr>
        <% end %>
        <% @rooms.each do |room| %>
          <tr class="border-t border-slate-200">
            <td class="py-2"><%= room.name %></td>
            <td class="py-2"><%= room.password %></td>
            <td class="py-2"><%= room.color %></td>
            <% if current_user&.admin? %>
              <td class="py-2 text-right min-w-28">
                <%= 
                  link_to "編輯", 
                  edit_room_path(room),
                  class: "block w-fit px-3 py-2 rounded bg-blue-500 hover:bg-blue-600 text-white"
                %>
              </td>
              <td class="py-2 text-right min-w-28">
                <%= 
                  link_to "刪除", 
                  room, 
                  method: :delete,
                  data: { turbo_method: :delete, turbo_confirm: "確定刪除？" },
                  class: "block w-fit px-3 py-2 rounded bg-red-500 hover:bg-red-600 text-white"
                %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="container mx-auto lg:py-10">
  <div class="w-1/2 mx-auto bg-white rounded-3xl py-12 px-16">
    <h1 class="text-4xl text-center">新增房間</h1>
    <div class="py-5">
      <%= render "form", room: @room %>
    </div>
    <div class="text-center">
      <%= link_to "回到房間列表", rooms_path, class: "text-blue-500" %>
    </div>
  </div>
</div>