config/routes.rb
Rails.application.routes.draw do
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Defines the root path route ("/")
    # root "posts#index"
    root to: "boards#index"

    resource :profile, controller: :profile, only: [ :show, :update ]
    resources :reservations, only: [ :index, :create, :delete, :destroy ]
    resources :time_slots, only: [ :index, :create, :new, :destroy, :edit ]
    resources :rooms, only: [ :index, :create, :new, :destroy, :edit, :update ]
    resources :users, only: [ :index, :create, :new, :destroy ] do
        member do
            patch "promote_to_regular"
            patch "promote_to_admin"
            patch "demote_to_guest"
        end
        resources :reservations
    end
    get "pending", to: "users#pending"
    get "/login", to: "session#new"
    post "/login", to: "session#create"
    get "/login/callback", to: "session#callback"
    delete "/logout", to: "session#destroy"  

    get "/boards/:id/(:date)", to: "boards#show",
        constraints: { :date => /\d{4}-\d{2}-\d{2}/ },
        as: :board

    get :rules, to: "rules#index" 
    get :limits, to: "limits#index" 
    put :limits, to: "limits#update" 
    
    # 忘記密碼
    get "/forgot-password", to: "users#forgot_password_form"
    post "/forgot-password", to: "users#forgot_password"
    get "/reset-password", to: "users#reset_password_form"
    post "/reset-password", to: "users#reset_password"

    delete '/users/:id/clear_reservations', 
        to: 'users#clear_reservations', 
        as: 'clear_reservations'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>琴房預約系統 | 交大鋼琴社</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= favicon_link_tag asset_path('logo.ico') %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="relative min-h-screen flex flex-col">
      <nav class="sticky top-0 z-10 bg-slate-300">
        <div class="lg:flex lg:h-20 lg:justify-between">
          <div class="h-full flex justify-between items-center">
            <%# 回主畫面 %>
            <%= link_to(root_path, class: "py-2") do %>
              <%= image_tag 'logo.jpg', class: "h-14 mx-5" ,alt: "Logo" %>
            <% end %>
            <%# 漢堡 %>
            <button id="burger" class="py-2 lg:hidden" onclick="toggleMenu()">
              <%= image_tag 'burger.svg', class: "h-12 mx-5" ,alt: "Burger Menu" %>
            </button>
          </div>
          <%# 中間的 nav item %>
          <ul id="menu" class="lg:flex hidden">
            <% room_names = Room.pluck(:name) %>
            <% room_names.each do |room_name| %>
              <li class="text-xl">
                <% if request.path == board_path(room_name) %>
                  <%= link_to(board_path(room_name), class: "block flex h-full items-center px-4 bg-blue-500 text-white") do %>
                    <div class="mx-auto py-2"><%= room_name %></div>
                  <% end %>
                <% else %>
                  <%= link_to(board_path(room_name), class: "block flex h-full items-center px-4 hover:bg-blue-300 hover:text-white") do %>
                    <div class="mx-auto py-2"><%= room_name %></div>
                  <% end %>
                <% end %>
              </li>
            <% end %>
            <li class="text-xl">
              <% if request.path == rules_path %>
                <%= link_to(rules_path, class: "block flex h-full items-center px-4 bg-blue-500 text-white") do %>
                  <div class="mx-auto py-2">使用規範</div>
                <% end %>
              <% else %>
                <%= link_to(rules_path, class: "block flex h-full items-center px-4 hover:bg-blue-300 hover:text-white") do %>
                  <div class="mx-auto py-2">使用規範</div>
                <% end %>
              <% end %>
            </li>
            <li class="text-xl">
              <% if request.path.start_with?("/users/") && request.path.include?("/reservations") %>
                <%= link_to(current_user ? user_reservations_path(user_id: current_user.id) : reservations_path, class: "block flex h-full items-center px-4 bg-blue-500 text-white") do %>
                  <div class="mx-auto py-2">我的預約</div>
                <% end %>
              <% else %>
                <%= link_to(current_user ? user_reservations_path(user_id: current_user.id) : reservations_path, class: "block flex h-full items-center px-4 hover:bg-blue-300 hover:text-white") do %>
                  <div class="mx-auto py-2">我的預約</div>
                <% end %>
              <% end %>
            </li>
            <li class="text-xl">
              <% if request.path == rooms_path %>
                <%= link_to(rooms_path, class: "block flex h-full items-center px-4 bg-blue-500 text-white") do %>
                  <div class="mx-auto py-2">琴房</div>
                <% end %>
              <% else %>
                <%= link_to(rooms_path, class: "block flex h-full items-center px-4 hover:bg-blue-300 hover:text-white") do %>
                  <div class="mx-auto py-2">琴房</div>
                <% end %>
              <% end %>
            </li>
            <% if current_user && current_user.admin? %>
              <li class="text-xl">
                <% if request.path == users_path %>
                  <%= link_to(users_path, class: "block flex h-full items-center px-4 bg-rose-500 text-white") do %>
                    <div class="mx-auto py-2">使用者</div>
                  <% end %>
                <% else %>
                  <%= link_to(users_path, class: "block flex h-full items-center px-4 hover:bg-rose-300 hover:text-white") do %>
                    <div class="mx-auto py-2">使用者</div>
                  <% end %>
                <% end %>
              </li>
              <li class="text-xl">
                <% if request.path == time_slots_path %>
                  <%= link_to(time_slots_path, class: "block flex h-full items-center px-4 bg-rose-500 text-white") do %>
                    <div class="mx-auto py-2">時段</div>
                  <% end %>
                <% else %>
                  <%= link_to(time_slots_path, class: "block flex h-full items-center px-4 hover:bg-rose-300 hover:text-white") do %>
                    <div class="mx-auto py-2">時段</div>
                  <% end %>
                <% end %>
              </li>
              <li class="text-xl">
                <% if request.path == reservations_path %>
                  <%= link_to(reservations_path, class: "block flex h-full items-center px-4 bg-rose-500 text-white") do %>
                    <div class="mx-auto py-2">預約</div>
                  <% end %>
                <% else %>
                  <%= link_to(reservations_path, class: "block flex h-full items-center px-4 hover:bg-rose-300 hover:text-white") do %>
                    <div class="mx-auto py-2">預約</div>
                  <% end %>
                <% end %>
              </li>
              <li class="text-xl">
                <% if request.path == limits_path %>
                  <%= link_to(limits_path, class: "block flex h-full items-center px-4 bg-rose-500 text-white") do %>
                    <div class="mx-auto py-2">限制</div>
                  <% end %>
                <% else %>
                  <%= link_to(limits_path, class: "block flex h-full items-center px-4 hover:bg-rose-300 hover:text-white") do %>
                    <div class="mx-auto py-2">限制</div>
                  <% end %>
                <% end %>
              </li>
            <% end %>
          </ul>
          <%# 使用者 %>
          <div id="user" class="lg:block hidden relative w-full lg:w-48 cursor-pointer" onmouseover="showUserDropdown()" onmouseout="hideUserDropdown()">
            <% if current_user.present? %>
              <div class="text-xl flex h-full items-center">
                <div class="py-2 w-full text-center">
                  <%= current_user&.name %>
                </div>
              </div>
              <ul class="absolute w-full hidden" id="user-dropdown">
                <li class="">
                  <%= link_to("個人資料", profile_path, class: "block w-full h-full px-4 py-3 rounded bg-slate-100 hover:bg-slate-500 hover:text-white text-center") %>
                </li>
                <li class="">
                  <%= link_to(
                  "登出", 
                  logout_path, 
                  method: :delete,
                  data: { turbo_method: :delete, turbo_confirm: "確定登出？" },
                  class: "block w-full h-full px-4 py-3 rounded block w-full h-full px-4 py-3 rounded bg-slate-100 hover:bg-slate-500 hover:text-white text-center"
                ) %>
                </li>
              </ul>
            <% else %>
              <div class="text-xl flex h-full items-center">
                <div class="py-4 w-full text-center">
                  <%= link_to("登入", login_path, class: "px-6 py-3 rounded-full bg-slate-300 hover:bg-slate-500 hover:text-white") %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </nav>
      <main class="relative flex-auto flex flex-col bg-slate-100">
        <%= yield %>
        <% flash.each do |type, msg| %>
          <div class="<%= flash_class(type) %>" role="alert">
            <span class="block sm:inline"><%= msg %></span>
          </div>
        <% end %>

      </main>

    </div>
    <script>
      // 使用者選單
      function showUserDropdown() {
        document.getElementById("user-dropdown").classList.remove("hidden");
      }
      function hideUserDropdown() {
        document.getElementById("user-dropdown").classList.add("hidden");
      }
    </script>
    <script>
      // 漢堡選單
      function toggleMenu() {
        document.getElementById("menu").classList.toggle("hidden");
        document.getElementById("user").classList.toggle("hidden");
      }
    </script>
  </body>
</html>